version: 1.0.{build}
image: Visual Studio 2015


environment:
  matrix:
  - PlatformToolset: v140

platform:
    - x64
    - Any CPU

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="Any CPU" set archi=x86
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%
    - nuget restore "%APPVEYOR_BUILD_FOLDER%"\ClipboardHelper.Tests\packages.config -PackagesDirectory "%APPVEYOR_BUILD_FOLDER%"\packages

build:
    parallel: true                  # enable MSBuild parallel builds
    verbosity: minimal

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild ClipboardHelper.sln /m /p:configuration="%configuration%" /p:platform="%platform%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"\ClipboardHelper
    - ps: >-

        if ($env:PLATFORM -eq "x64" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "bin\x64\$env:CONFIGURATION\ClipboardHelper.dll" -FileName ClipboardHelper.dll
        }

        if ($env:PLATFORM -eq "Any CPU" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "bin\$env:CONFIGURATION\ClipboardHelper.dll" -FileName ClipboardHelper.dll
        }

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "v140") {
            if($env:PLATFORM -eq "x64"){
            $ZipFileName = "ClipboardHelper_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
            Remove-Item bin\x64\$env:CONFIGURATION\*.exp
            Remove-Item bin\x64\$env:CONFIGURATION\*.lib
            7z a $ZipFileName bin\x64\$env:CONFIGURATION\*
            }
            if($env:PLATFORM -eq "Any CPU"){
            $ZipFileName = "ClipboardHelper_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
            Remove-Item bin\$env:CONFIGURATION\*.exp
            Remove-Item bin\$env:CONFIGURATION\*.lib
            7z a $ZipFileName bin\$env:CONFIGURATION\*
            }
        }

artifacts:
  - path: ClipboardHelper_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: v140
        configuration: Release
